//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCustomerInformationDataAccessLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLoginActivity
    {
        public int SNO { get; set; }
        public int User_Name { get; set; }
        public string Password { get; set; }
        public System.DateTime Login_Time { get; set; }
    }
}
